function out = dynxu(sys, x, u)
%DYNXU
%    OUT = DYNXU(SYS, X, U)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    26-Sep-2020 13:37:02

m = sys.m;
I = sys.I;
d = sys.d;
df = sys.df;
l0 = sys.l0;

x1 = x(1,:);
x2 = x(2,:);
x5 = x(5,:);

t2 = cos(x2);
t3 = sin(x2);
l2 = sqrt((x1.*t2 + df).^2 + (x1.*t3).^2);
contact1 = x1 <= l0;
contact2 = l2 <= l0;

t4 = df.^2;
t5 = x2.*2.0;
t6 = x1.^2;
t8 = df.*x1.*2.0;
t12 = 1.0./I;
t14 = 1.0./m;
t15 = -x5;
t16 = 1.0./x1;
t7 = t2.^2;
t9 = sin(t5);
t10 = t3.^2;
t11 = df.*t2;
t13 = t2.*x1;
t17 = 1.0./t6;
t18 = t3.*x1.*2.0;
t20 = t2.*t6;
t21 = t2.*t8;
t22 = -t6;
t25 = t15+x2;
t26 = t2.*t4;
t19 = df.*t9;
t23 = df+t13;
t24 = t11+x1;
t27 = cos(t25);
t28 = sin(t25);
t29 = t7-1.0;
t30 = t4+t22;
t32 = t4+t6+t21;
t38 = t8+t20+t26;
t31 = t18+t19;
t33 = d.*t12.*t28;
t34 = 1.0./t32;
t36 = d.*t12.*t16.*t27;
t37 = sqrt(t32);
t35 = t34.^2;
t39 = 1.0./t37;
t42 = -t37;
t45 = t6.*t29.*t34;
t47 = t22.*t29.*t34;
t40 = t39.^3;
t41 = t39.^5;
t43 = t23.*t39;
t52 = 1.0./sqrt(t47);
t44 = acos(t43);
t46 = -t44;
t48 = t46+x5;
t49 = cos(t48);
t50 = sin(t48);
t51 = d.*t50;
t53 = t42+t51;

out = zeros(size(x,1), size(x,1), size(u,1), size(x,2));

out(3,2,1,:) = -t3.*t14.*contact1;
out(4,2,1,:) = t2.*t14.*contact1;
out(6,2,1,:) = -t33.*contact1;

out(6,5,1,:) = t33.*contact1;

out(3,1,2,:) = df.*t14.*t29.*t40.*x1.*contact2;
out(4,1,2,:) = df.*t10.*t14.*t23.*t35.*t52.*x1.*contact2;
out(6,1,2,:) = -df.*t12.*t29.*t40.*t51.*t52.*x1.*contact2;

out(3,2,2,:) = t6.*t14.*t31.*t40.*(-1.0./2.0).*contact2;
out(4,2,2,:) = t3.*t6.*t14.*t23.*t24.*t35.*t52.*contact2;
out(6,2,2,:) = (t6.*t12.*t31.*t40.*t51.*t52)./2.0.*contact2;

out(6,5,2,:) = -t12.*t51.*contact2;

out(3,1,3,:) = -t3.*t14.*t17.*contact1;
out(4,1,3,:) = t2.*t14.*t17.*contact1;
out(6,1,3,:) = -t17.*t33.*contact1;

out(3,2,3,:) = t2.*t14.*t16.*contact1;
out(4,2,3,:) = t3.*t14.*t16.*contact1;
out(6,2,3,:) = t36.*contact1;

out(6,5,3,:) = -t36.*contact1;

out(3,1,4,:) = t10.*t14.*t30.*t41.*t52.*x1.*contact2;
out(4,1,4,:) = t14.*t35.*t38.*contact2;
out(6,1,4,:) = t12.*(t39.*(t24.*t39-d.*df.*t29.*t40.*t49.*t52.*x1)-t24.*t40.*(t37-t51)).*contact2;

out(3,2,4,:) = t3.*t6.*t14.*t38.*t41.*t52.*contact2;
out(4,2,4,:) = -t3.*t14.*t30.*t35.*x1.*contact2;
out(6,2,4,:) = -t12.*(t39.*(df.*t3.*t39.*x1-(d.*t6.*t31.*t40.*t49.*t52)./2.0)-df.*t3.*t40.*x1.*(t37-t51)).*contact2;

out(6,5,4,:) = -d.*t12.*t39.*t49.*contact2;

end
